//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.24 at 02:22:34 PM PST 
//


package com.intel.mountwilson.as.hostmanifestreport.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.intel.mountwilson.as.hostmanifestreport.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HostManifestReport_QNAME = new QName("", "host_manifest_report");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.intel.mountwilson.as.hostmanifestreport.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ManifestType }
     * 
     */
    public ManifestType createManifestType() {
        return new ManifestType();
    }

    /**
     * Create an instance of {@link HostManifestReportType }
     * 
     */
    public HostManifestReportType createHostManifestReportType() {
        return new HostManifestReportType();
    }

    /**
     * Create an instance of {@link HostType }
     * 
     */
    public HostType createHostType() {
        return new HostType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HostManifestReportType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "host_manifest_report")
    public JAXBElement<HostManifestReportType> createHostManifestReport(HostManifestReportType value) {
        return new JAXBElement<HostManifestReportType>(_HostManifestReport_QNAME, HostManifestReportType.class, null, value);
    }

}
