//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.24 at 02:22:33 PM PST 
//


package com.intel.mountwilson.as.hosttrustreport.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for HostType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HostType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Host_Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MLE_Info" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Created_On" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="Trust_Status" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Verified_On" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HostType")
public class HostType {

    @XmlAttribute(name = "Host_Name")
    protected String hostName;
    @XmlAttribute(name = "MLE_Info")
    protected String mleInfo;
    @XmlAttribute(name = "Created_On")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdOn;
    @XmlAttribute(name = "Trust_Status")
    protected Integer trustStatus;
    @XmlAttribute(name = "Verified_On")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar verifiedOn;

    /**
     * Gets the value of the hostName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * Sets the value of the hostName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostName(String value) {
        this.hostName = value;
    }

    /**
     * Gets the value of the mleInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMLEInfo() {
        return mleInfo;
    }

    /**
     * Sets the value of the mleInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMLEInfo(String value) {
        this.mleInfo = value;
    }

    /**
     * Gets the value of the createdOn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedOn() {
        return createdOn;
    }

    /**
     * Sets the value of the createdOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedOn(XMLGregorianCalendar value) {
        this.createdOn = value;
    }

    /**
     * Gets the value of the trustStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTrustStatus() {
        return trustStatus;
    }

    /**
     * Sets the value of the trustStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTrustStatus(Integer value) {
        this.trustStatus = value;
    }

    /**
     * Gets the value of the verifiedOn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVerifiedOn() {
        return verifiedOn;
    }

    /**
     * Sets the value of the verifiedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVerifiedOn(XMLGregorianCalendar value) {
        this.verifiedOn = value;
    }

}
