#!/bin/sh

# REQUIRES: file, input

# XXX are we using this?
DEFAULT_MTWILSON_API_BASEURL="http://127.0.0.1"

apiclient_dir=/usr/local/share/mtwilson/apiclient
apiclient_java=${apiclient_dir}/java


# Usage: mtwilson api <command> [args]
mw_api() {
        call_apiclient $@
}


### FUNCTION LIBRARY: api

call_apiclient() {
  if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; return 1; fi
  APICLIENT_JARS=$(JARS=(${apiclient_java}/*.jar); IFS=:; echo "${JARS[*]}")
  mainclass=com.intel.mtwilson.client.TextConsole
  $java -cp "$APICLIENT_JARS" -Dlogback.configurationFile=${conf_dir}/logback.xml $mainclass $@
}


# new in 1.2
configure_api_baseurl() {
  # setup mtwilson.api.baseurl
  local config_file="${1:-/etc/intel/cloudsecurity/my.properties}" 
  
  local input_api_baseurl
  if [ -n "${MTWILSON_API_BASEURL}" ]; then
    mtwilson_api_baseurl="${MTWILSON_API_BASEURL}"
  elif [ -n "${MTWILSON_SERVER}" ]; then
    mtwilson_api_baseurl="https://${MTWILSON_SERVER}:$DEFAULT_API_PORT"
  else
    local configured_api_baseurl=`read_property_from_file mtwilson.api.baseurl "${config_file}"`
    prompt_with_default input_api_baseurl "Mt Wilson Server (IP, Hostname, or URL):" "${configured_server_url}"
    
    if [[ "$input_api_baseurl" == http* ]]; then
      mtwilson_api_baseurl="$input_api_baseurl"
    else
      mtwilson_api_baseurl="https://${input_api_baseurl}:$DEFAULT_API_PORT"
    fi
  fi
  export MTWILSON_API_BASEURL=$mtwilson_api_baseurl
  update_property_in_file mtwilson.api.baseurl "${config_file}" "${mtwilson_api_baseurl}"
}
