#!/bin/sh
# mtwilson plugin




mw_asctl() {
addopt "c" "checksum"
addopt "b:" "bios name"
addlongopt "version" "display version"
addlongopt "username:" "specify username"
loadplugin msctl
  echo "hello world"
}
