#!/bin/sh

# REQUIRES: setup


# Usage: mtwilson erase-data
mw_erase_data() {
        call_setupcommand EraseHostRegistrationData
        call_setupcommand EraseWhitelistData
        call_setupcommand EraseLogs
}

# Usage: mtwilson erase-users
mw_erase_users() {
        call_setupcommand EraseUserAccounts
}
