#!/bin/sh

# XXX TODO: maybe find a way to list all mw_* commands?  strip prefix mw_, convert underscore to hyphens? or
# should every plugin also register help text that describes the commands available and their arguments?

# Usage: mtwilson help
mw_help() {
        echo "Usage: mtwilson {api|erase-data|fingerprint|glassfish-detect|glassfish-enable-logging|glassfish-start|glassfish-stop|" \
             "glassfish-restart|glassfish-status|glassfish-sslcert|help|mysql-decect|mysql-sslcert|java-detect|setup|status|uninstall|version}"
}

### FUNCTION LIBRARY: help

# Usage: addhelp "command name" "one line description"
#addhelp() {
#  local cmdname="$1"
#  local description="$2"
#}
