#!/bin/sh

# REQUIRES: java, glassfish, monit, tomcat

# Usage: mtwilson uninstall
mw_uninstall() {
        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
        if using_glassfish; then
          glassfish_require
          echo "Stopping Glassfish..."
          glassfish_shutdown
          # application files
          echo "Removing Glassfish in /usr/share/glassfish3..."
          rm -rf /usr/share/glassfish3
        fi
        echo "Removing Mt Wilson applications in /opt/intel/cloudsecurity..."
        rm -rf /opt/intel/cloudsecurity
        echo "Removing Mt Wilson utilities in /usr/local/share/mtwilson..."
        rm -rf /usr/local/share/mtwilson
        # configuration files
        echo "Removing Mt Wilson configuration in /etc/intel/cloudsecurity..."
        rm -rf /etc/intel/cloudsecurity
        # data files
        echo "Removing Mt Wilson data in /var/opt/intel..."
        rm -rf /var/opt/intel
		echo "Stopping Monit service..."
		service monit stop &> /dev/null
		if [ -f /etc/monit/monitrc ]; then
		 #remove monit config so when it starts back up it has nothing to monitor
		 # idealy here we should be uninstalling instead
		 rm -fr /etc/monit/monitrc
		fi
        # java:  rm -rf /usr/share/jdk1.6.0_29
        # control scripts
        echo "Removing Mt Wilson control scripts..."
        echo asctl wlmctl msctl pcactl mcctl wpctl tdctl mtwilson | tr ' ' '\n' | xargs -I file rm -rf /usr/local/bin/file
        # plugins
        echo "Removing Mt Wilson Components..."
        rm -rf /usr/share/mtwilson
        echo_success "Done"
}
