/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.intel.mtwilson.datatypes;

import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author dsmagadx
 */
public enum ErrorCode {

    OK(0), 
    SYSTEM_ERROR(1), 
//    AUTH_FAILED(1000), 
//    SQL_ERROR(1001), 
    UNKNOWN_ERROR(2),  // Used in APIClient
//    GENERAL_ERROR(1003), 
//    DUPLICATE_HOST_NAME(1004), 
//    TA_ERROR (1005), 
//    VALIDATION_ERROR(1006),  // used to be 1005 "Invalid Parameter" in AH ErrorCode
//    WLM_SERVICE_ERROR(1007), 
//    TRUST_ERROR(1008),
//    DATA_ERROR(1009),
//    AS_ERROR(1200), // this used to be 1004, same as duplicate host name error. changed to 1200
//    WML_ERROR(1201), // this one is from AH ErrorCode, is there a difference from 1007 WLM Service Error?
//    HOST_NOT_FOUND(2000), 
//    NETWORK_ERROR(2001), 
//    VMW_TPM_NOT_SUPPORTED(3000), 
//    VMWARE_ERROR(3001),
//    DUPLICATE_ENTITY_ERROR(4001),
    
    // HTTP error codes
    HTTP_INVALID_REQUEST(400),
    HTTP_UNAUTHORIZED(401),
    HTTP_FORBIDDEN(403),
    HTTP_NOT_FOUND(404),
    HTTP_INTERNAL_SERVER_ERROR(500),

    AS_ASYNC_TIMEOUT(1002),
    AS_HOST_NOT_FOUND(1003),
    AS_BIOS_INCORRECT(1004),
    AS_VMM_INCORRECT(1004),
    AS_HOST_EXISTS(1005),
    AS_IPADDRESS_EXISTS(1006),
    AS_MISSING_MANIFEST(1007),
    AS_MISSING_INPUT(1008),
    AS_OPERATION_NOT_SUPPORTED(1009 ),
    AS_QUOTE_VERIFY_COMMAND_FAILED(1010),
    AS_HOST_COMMUNICATION_ERROR(1011), // error message
    AS_TRUST_AGENT_ERROR(1012),
    AS_ENCRYPTION_ERROR(1013),
    AS_VMW_TPM_NOT_SUPPORTED(1014),
    AS_PCR_NOT_FOUND(1015),
    AS_MISSING_PCR_MANIFEST(1016 ),
    AS_CONFIGURATION_ERROR(1017),
    AS_TRUST_AGENT_DAA_ERROR(1018),
    AS_MISSING_MLE_REQD_MANIFEST_LIST(1019),
    AS_HOST_MANIFEST_MISSING_PCRS (1020),
    AS_VMWARE_INVALID_CONNECT_STRING(1021),
    AS_HOST_NOT_FOUND_IN_VCENTER(1022),
    AS_PCR_MANIFEST_MISSING(1023),
    AS_TRUST_AGENT_CONNNECT_TIMED_OUT(1024),
    AS_TRUST_AGENT_INVALID_RESPONSE(1025),
    AS_INTEL_TXT_NOT_ENABLED(1026),
    AS_INVALID_AIK_CERTIFICATE(1027),
    AS_TPM_NOT_SUPPORTED(1028),
    AS_CITRIX_ERROR(1029),
    AS_INVALID_ASSET_TAG_CERTIFICATE_HASH(1030),
    AS_INVALID_ASSET_TAG_CERTIFICATE(1031),
    AS_HOST_SPECIFIED_IS_CURRENTLY_NOT_MAPPED_TO_ASSET_TAG_CERTIFICATE(1032),
    


    // Error codes for White List Service
    WS_OEM_DOES_NOT_EXIST(2001),
    WS_OEM_ALREADY_EXISTS(2002),
    WS_OEM_ASSOCIATION_EXISTS(2003),
    WS_OS_DOES_NOT_EXIST(2004),
    WS_OS_ALREADY_EXISTS(2005),
    WS_OS_ASSOCIATION_EXISTS(2006),
    WS_MLE_ALREADY_EXISTS(2007),
    WS_ESX_MLE_NOT_SUPPORTED(2008),
    WS_MLE_DOES_NOT_EXIST(2009),
    WS_MLE_ASSOCIATION_EXISTS(2010),
    WS_MLE_DATA_MISSING(2011),
    WS_OEM_OS_DATA_CANNOT_COEXIST(2012),
    WS_PCR_WHITELIST_ALREADY_EXISTS(2013),
    WS_PCR_WHITELIST_DOES_NOT_EXIST(2014),
    WS_EVENT_TYPE_DOES_NOT_EXIST(2015),
    WS_MODULE_WHITELIST_ALREADY_EXISTS(2016),
    WS_MODULE_WHITELIST_DOES_NOT_EXIST(2017),
    WS_NAME_SPACE_DOES_NOT_EXIST(2018),
    WS_MLE_SOURCE_MAPPING_ALREADY_EXISTS(2019),
    WS_MLE_SOURCE_MAPPING_DOES_NOT_EXIST(2020),
    WS_INVALID_WHITE_LIST_VALUE(2021),
    
    
    // Below are error codes for the Management service
    // 3000 to 3100 General Management Service errors
    // 3100 to 3200 APIClient
    MS_EXPIRED_CERTIFICATE(3101),
    MS_CERTIFICATE_NOT_YET_VALID(3102),
    MS_DUPLICATE_CERTIFICATE(3103),
    MS_CERTIFICATE_ENCODING_ERROR(3104),
    MS_BAD_CERTIFICATE_FILE(3105),
    MS_MISSING_CERTIFICATE_FILE(3106),
    MS_UN_SUPPORTED_HASH_ALGORITHM(3107),
    MS_API_CLIENT_INVALID_ROLE(3108),
    MS_API_CLIENT_ROLE_ALEADY_EXISTS(3109),
    MS_API_CLIENT_CREATE_ERROR(3110),
    MS_API_CLIENT_UPDATE_ERROR(3111),
    MS_API_CLIENT_FIND_ERROR(3112),
    MS_INVALID_CERTIFICATE_DATA(3113),
    MS_ERROR_PARSING_INPUT(3114),

    // 3201 to 3300 Automation
    MS_HOST_COMMUNICATION_ERROR(3201),
    MS_INVALID_WHITELIST_TARGET(3202),
    MS_INVALID_PCRS(3203),
    MS_OEM_NOT_FOUND(3204),
    MS_OS_NOT_FOUND(3205),
    MS_BIOS_MLE_NOT_FOUND(3206),
    MS_VMM_MLE_NOT_FOUND(3207),
    MS_API_EXCEPTION(3208),
    MS_INVALID_ATTESTATION_REPORT(3209),
    MS_HOST_CONFIGURATION_ERROR(3210),
    MS_FAILED_GET_HOST_PLATFORM_NAME(3211),
    MS_FAILED_GET_HOST_MLE_INFO(3212),
    MS_FAILED_BULK_REGISTER_HOST(3213),
    MS_FAILED_REGISTER_HOST(3214),
    MS_FAILED_UPDATE_HOST(3215),
    MS_FAILED_CONFIGURE_WHITELIST(3216),
    
    TLS_COMMMUNICATION_ERROR(4001);
   
    
    

    
    public int getErrorCode() {
        
        return errorCode;
    }

    public void setErrorCode(int errorCode) {
        this.errorCode = errorCode;
    }

    private ErrorCode(int errorCode) {
        this.errorCode = errorCode;
    }
    
    private static class ErrorCodeCache {
        private static Map<Integer,ErrorCode> ecCache = new HashMap<Integer,ErrorCode>();

        static {
            for (final ErrorCode ec : ErrorCode.values()) {
                ecCache.put(ec.getErrorCode(), ec);
            }
        }
    }
    
    public static ErrorCode getErrorCode(int ec) {
        return ErrorCodeCache.ecCache.get(ec);
    }
    
    int errorCode;
}
