//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.05 at 03:02:52 PM PDT 
//


package com.intel.mountwilson.ta.data.hostinfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="timeStamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="clientIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="errorCode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="errorMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="osName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="osVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="biosOem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="biosVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vmmName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vmmVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "host_info", propOrder = {
    "timeStamp",
    "clientIp",
    "errorCode",
    "errorMessage",
    "osName",
    "osVersion",
    "biosOem",
    "biosVersion",
    "vmmName",
    "vmmVersion",
    "processorInfo",
    "hostUUID"
})

public class HostInfo {

    @XmlElement(name = "timeStamp", required = true)
    protected String timeStamp;
    @XmlElement(name = "clientIp",required = true)
    protected String clientIp;
    @XmlElement(name = "errorCode",required = true)
    protected byte errorCode;
    @XmlElement(name = "errorMessage",required = true)
    protected String errorMessage;
    @XmlElement(name = "osName",required = true)
    protected String osName;
    @XmlElement(name = "osVersion",required = true)
    protected String osVersion;
    @XmlElement(name = "biosOem",required = true)
    protected String biosOem;
    @XmlElement(name = "biosVersion",required = true)
    protected String biosVersion;
    @XmlElement(name = "vmmName",required = true)
    protected String vmmName;
    @XmlElement(name = "vmmVersion", required = true)
    protected String vmmVersion;
    @XmlElement(name = "processorInfo",required = true)
    protected String processorInfo;
    @XmlElement(name = "hostUUID",required = true)
    protected String hostUUID;

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeStamp(String value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the clientIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * Sets the value of the clientIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientIp(String value) {
        this.clientIp = value;
    }

    /**
     * Gets the value of the errorCode property.
     * 
     */
    public byte getErrorCode() {
        return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     * 
     */
    public void setErrorCode(byte value) {
        this.errorCode = value;
    }

    /**
     * Gets the value of the errorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * Sets the value of the errorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMessage(String value) {
        this.errorMessage = value;
    }

    /**
     * Gets the value of the osName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOsName() {
        return osName;
    }

    /**
     * Sets the value of the osName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOsName(String value) {
        this.osName = value;
    }

    /**
     * Gets the value of the osVersion property.
     * 
     */
    public String getOsVersion() {
        return osVersion;
    }

    /**
     * Sets the value of the osVersion property.
     * 
     */
    public void setOsVersion(String value) {
        this.osVersion = value;
    }

    /**
     * Gets the value of the biosOem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBiosOem() {
        return biosOem;
    }

    /**
     * Sets the value of the biosOem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBiosOem(String value) {
        this.biosOem = value;
    }

    /**
     * Gets the value of the biosVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBiosVersion() {
        return biosVersion;
    }

    /**
     * Sets the value of the biosVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBiosVersion(String value) {
        this.biosVersion = value;
    }

    /**
     * Gets the value of the vmmName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVmmName() {
        return vmmName;
    }

    /**
     * Sets the value of the vmmName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVmmName(String value) {
        this.vmmName = value;
    }

    /**
     * Gets the value of the vmmVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVmmVersion() {
        return vmmVersion;
    }

    /**
     * Sets the value of the vmmVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVmmVersion(String value) {
        this.vmmVersion = value;
    }

    public String getProcessorInfo() {
        return processorInfo;
    }

    public void setProcessorInfo(String processorInfo) {
        this.processorInfo = processorInfo;
    }
    
    public String getHostUUID() {
        return hostUUID;
    }

    public void setHostUUID(String hostUUID) {
        this.hostUUID = hostUUID;
    }
}
